[package]
name = "test-helper"
version = "0.1.0"
authors = ["Chris Beck <beck.ct@gmail.com>"]
edition = "2018"

[dependencies]
rand_core = { version = "0.5", default-features = false }
rand_hc = "0.2"
